backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "nastenka"
    label: "Nástěnka"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Datum vytvoření", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "hidden", default: ["post"]}
      - {label: "Anotace", name: "description", widget: "text"}
      - {label: "Tělo článku", name: "body", widget: "markdown"}
      - {
        label: "Příloha č.1",
        name: "file1",
        widget: "file",
        required: false,
        }
      - {
        label: "Příloha č.2",
        name: "file2",
        widget: "file",
        required: false,
        }
      - {
        label: "Příloha č.3",
        name: "file3",
        widget: "file",
        required: false,
        }
